### PR TITLE
Fix `Concepts` link docs in website

### LINKED ISSUE #435: Link Not Working in Website
### Description

**Observed Behavior**:
The link at the end of the [Deploy your first RGD](https://kro.run/docs/getting-started/deploy-a-resource-graph-definition#delete-the-application-instance) page isn't working.

**Expected Behavior**:
The link should take the user to the next page

**Reproduction Steps** (Please include `ResourceGraphDefinition` and `Instances` files):

**Versions**:
- kro version:
- Kubernetes Version (`kubectl version`):

**Involved Controllers**:
- Controller URLs and Versions (if applicable):

**Error Logs** (if applicable)**:
```
Paste any relevant logs here
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Which option describes the most your issue?

Others (Website)

### PR DESCRIPTION
**Pull request by AshwinSriram11**
Fixes #435. The link directly links to the next page(RGD)

### CODE REVIEW

File: pkg/runtime/interfaces.go [hunk 1]
```diff
@@ -109,7 +109,6 @@ type ResourceDescriptor interface {
 	// be evaluated before deciding whether to create a resource
 	GetIncludeWhenExpressions() []string
 
-
```
Comment (a-hilaly) [inline pkg/runtime/interfaces.go]: Can we please not include any changes to Go files in this PR?

**Review by a-hilaly — COMMENTED** [review]
Thank you @AshwinSriram11 !

File: pkg/runtime/interfaces.go (hunk 1 above)
Comment (AshwinSriram11) [reply pkg/runtime/interfaces.go]: My bad! I ran `make fmt generate` before pushing the changes.

**Review by a-hilaly — APPROVED** [review]
Thanks @AshwinSriram11 !
